spring:
  application:
    name: auth-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
#  datasource:
#    url: jdbc:mysql://localhost:3306/msa
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

#service:
#  jwt:
#    access-expiration: 3600000
#    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
#
#server:
#  port: 19095
